from __future__ import annotations


def configure_user_agent_hooks_for_core(
    *,
    configure_user_agent_hooks_fn,
    context: dict[str, object],
    sim_on_active_alpha_fn,
    sim_alpha_fn,
    sigmoid01_fn,
    ensure_content_index_fn,
    vectorized_cbf_faced_fn,
    seen_mask_np_fn,
    unseen_mask_for_ids_fn,
    softmax_arr_fn,
    pick_from_probs_fn,
    get_seen_mask_row_fn,
    get_content_ids_fn,
    require_content_ids_fn,
    get_isc_fn,
    random_module,
    random_choice,
):
    def _ctx(name: str):
        return context[name]

    kwargs = {
        "NUM_GENRES": _ctx("NUM_GENRES"),
        "NUM_INSTINCT_DIM": _ctx("NUM_INSTINCT_DIM"),
        "NUM_CONTENTS": _ctx("NUM_CONTENTS"),
        "RANDOM_SEED": _ctx("RANDOM_SEED"),
        "RANDOM_REPEAT_POLICY": _ctx("RANDOM_REPEAT_POLICY"),
        "Agent_G_PARAMS": _ctx("Agent_G_PARAMS"),
        "Agent_V_PARAMS": _ctx("Agent_V_PARAMS"),
        "Agent_I_PARAMS": _ctx("Agent_I_PARAMS"),
        "AGENT_ALPHA": _ctx("AGENT_ALPHA"),
        "LIKE_W_CG": _ctx("LIKE_W_CG"),
        "LIKE_W_CV": _ctx("LIKE_W_CV"),
        "LIKE_W_CI": _ctx("LIKE_W_CI"),
        "LOGIT_K": _ctx("LOGIT_K"),
        "LOGIT_X0": _ctx("LOGIT_X0"),
        "LIKE_DIVISOR": _ctx("LIKE_DIVISOR"),
        "MU0": _ctx("MU0"),
        "MU_SLOPE": _ctx("MU_SLOPE"),
        "MU_ALPHA_C": _ctx("MU_ALPHA_C"),
        "MU_BETA_V": _ctx("MU_BETA_V"),
        "SIGMA0": _ctx("SIGMA0"),
        "SIGMA_LAMDA": _ctx("SIGMA_LAMDA"),
        "SIGMA_ALPHA_C": _ctx("SIGMA_ALPHA_C"),
        "SIGMA_BETA_V": _ctx("SIGMA_BETA_V"),
        "A0": _ctx("A0"),
        "A_LAMDA": _ctx("A_LAMDA"),
        "A_ALPHA_C": _ctx("A_ALPHA_C"),
        "A_BETA_V": _ctx("A_BETA_V"),
        "DIG_LOGIT_K": _ctx("DIG_LOGIT_K"),
        "DIG_LOGIT_X0": _ctx("DIG_LOGIT_X0"),
        "DIG_DIVISOR": _ctx("DIG_DIVISOR"),
        "PSEUDO_HISTORY_WINDOW_STEPS": _ctx("PSEUDO_HISTORY_WINDOW_STEPS"),
        "PSEUDO_DISCOUNT_GAMMA": _ctx("PSEUDO_DISCOUNT_GAMMA"),
        "LAMBDA_CBF": _ctx("LAMBDA_CBF"),
        "CBF_FACE": _ctx("CBF_FACE"),
        "CBF_W_G": _ctx("CBF_W_G"),
        "CBF_W_I": _ctx("CBF_W_I"),
        "CBF_TOP_K": _ctx("CBF_TOP_K"),
        "DEVICE": _ctx("DEVICE"),
        "generate_agent_g_vector": _ctx("generate_agent_g_vector"),
        "generate_agent_i_vector": _ctx("generate_agent_i_vector"),
        "generate_agent_v_vector": _ctx("generate_agent_v_vector"),
        "sim_on_active_alpha": sim_on_active_alpha_fn,
        "sim_alpha": sim_alpha_fn,
        "sigmoid01": sigmoid01_fn,
        "ensure_content_index": ensure_content_index_fn,
        "vectorized_cbf_faced": vectorized_cbf_faced_fn,
        "seen_mask_np": seen_mask_np_fn,
        "unseen_mask_for_ids": unseen_mask_for_ids_fn,
        "softmax_arr": softmax_arr_fn,
        "torch_pick_from_probs": pick_from_probs_fn,
        "require_content_ids": require_content_ids_fn,
        "compute_agent_pseudo": _ctx("compute_agent_pseudo"),
        "compute_agent_pseudo_vector_g": _ctx("compute_agent_pseudo_vector_g"),
        "compute_agent_pseudo_vector_i": _ctx("compute_agent_pseudo_vector_i"),
        "update_agent_like_history_gi": _ctx("update_agent_like_history_gi"),
        "on_agent_pool_grew": _ctx("on_agent_pool_grew"),
        "init_agent_perm_params": _ctx("init_agent_perm_params"),
        "next_agent_perm_cid": _ctx("next_agent_perm_cid"),
        "next_agent_unseen_random_cid": _ctx("next_agent_unseen_random_cid"),
        "run_agent_like_prob_scores": _ctx("run_agent_like_prob_scores"),
        "run_agent_like_and_dig_scores": _ctx("run_agent_like_and_dig_scores"),
        "run_compute_and_cache_cbf_scores": _ctx("run_compute_and_cache_cbf_scores"),
        "run_compute_and_cache_cf_user_scores": _ctx("run_compute_and_cache_cf_user_scores"),
        "run_compute_and_cache_cf_item_scores": _ctx("run_compute_and_cache_cf_item_scores"),
        "cf_user_candidates": lambda isc_obj, uid, step, agents, face="affinity": _ctx("run_cf_user_candidates")(
            isc_obj,
            uid,
            step,
            agents,
            face=face,
            lam=_ctx("LAMBDA_CF_USER"),
            neigh_k=_ctx("CF_USER_NEIGHBOR_TOP_K"),
            cand_k=_ctx("CF_USER_CANDIDATE_TOP_K"),
            ensure_content_index=ensure_content_index_fn,
            get_content_ids=get_content_ids_fn,
            seen_mask_np=seen_mask_np_fn,
            get_seen_mask_row=get_seen_mask_row_fn,
            softmax_arr=softmax_arr_fn,
        ),
        "cf_item_candidates": lambda isc_obj, uid, step, agents, face="affinity": _ctx("run_cf_item_candidates")(
            isc_obj,
            uid,
            step,
            agents,
            face=face,
            lam=_ctx("LAMBDA_CF_ITEM"),
            neigh_k=_ctx("CF_ITEM_NEIGHBOR_TOP_K"),
            cand_k=_ctx("CF_ITEM_CANDIDATE_TOP_K"),
            ensure_content_index=ensure_content_index_fn,
            get_content_ids=get_content_ids_fn,
            seen_mask_np=seen_mask_np_fn,
            get_seen_mask_row=get_seen_mask_row_fn,
            softmax_arr=softmax_arr_fn,
            cf_history_window_steps=_ctx("CF_HISTORY_WINDOW_STEPS"),
            device=_ctx("DEVICE"),
        ),
        "get_isc": get_isc_fn,
        "random_module": random_module,
        "random_choice": random_choice,
    }
    configure_user_agent_hooks_fn(**kwargs)
